"""user entity modified

Revision ID: 592e78bb4d6f
Revises: b84223dc89af
Create Date: 2023-03-15 07:15:31.104332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592e78bb4d6f'
down_revision = 'b84223dc89af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='password_hash')
        # batch_op.add_column(sa.Column('password_hash', sa.String(length=60), nullable=False))
        # batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
