"""event entity added

Revision ID: 5df21936accd
Revises: e1097ce7fab3
Create Date: 2023-03-24 19:33:44.424834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df21936accd'
down_revision = 'e1097ce7fab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('home_team', sa.Integer(), nullable=False),
    sa.Column('away_team', sa.Integer(), nullable=False),
    sa.Column('winner_team', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['away_team'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.id'], ),
    sa.ForeignKeyConstraint(['winner_team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
