"""expense added  entity added

Revision ID: 7006c114dee3
Revises: f5a0e77930dc
Create Date: 2023-03-15 15:21:57.992445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7006c114dee3'
down_revision = 'f5a0e77930dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
