"""user entity modified

Revision ID: b84223dc89af
Revises: 2e2c898bd331
Create Date: 2023-03-14 22:12:38.463750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84223dc89af'
down_revision = '2e2c898bd331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash', new_column_name='password')
        batch_op.alter_column('admin', new_column_name='is_admin')
        # batch_op.add_column(sa.Column('password', sa.String(length=60), nullable=False))
        # batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        # batch_op.drop_column('password_hash')
        # batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
